version: "3.9"

services:
  bugbounty:
    image: deivao-bugbounty
    build:
      context: .
      dockerfile: dockerfile
    container_name: deivao-bugbounty
    volumes:
      - .:/app
      - ./resultados:/app/bug_bounty_results
      - ./alvos.txt:/app/alvos.txt
      - ./wordlists:/app/wordlists  